export function getcarNum(){
  let carNum = [
          {
            label:'京',
            value:'京'
          },{
            label:'豫',
            value:'豫'
          },{
            label:'苏',
            value:'苏'
          },{
            label:'冀',
            value:'冀'
          },{
            label:'鄂',
            value:'鄂'
          },{
            label:'津',
            value:'津'
          },{
            label:'晋',
            value:'晋'
          },{
            label:'蒙',
            value:'蒙'
          },{
            label:'辽',
            value:'辽'
          },{
            label:'黑',
            value:'黑'
          },{
            label:'沪',
            value:'沪'
          },{
            label:'浙',
            value:'浙'
          },{
            label:'皖',
            value:'皖'
          },{
            label:'闽',
            value:'闽'
          },{
            label:'粤',
            value:'粤'
          },{
            label:'桂',
            value:'桂'
          },{
            label:'琼',
            value:'琼'
          },{
            label:'赣',
            value:'赣'
          },{
            label:'湘',
            value:'湘'
          },{
            label:'甘',
            value:'甘'
          },{
            label:'青',
            value:'青'
          },{
            label:'陕',
            value:'陕'
          },{
            label:'藏',
            value:'藏'
          },{
            label:'云',
            value:'云'
          },{
            label:'贵',
            value:'贵'
          },{
            label:'新',
            value:'新'
          },{
            label:'宁',
            value:'宁'
          },{
            label:'川',
            value:'川'
          },{
            label:'鲁',
            value:'鲁'
          },{
            label:'吉',
            value:'吉'
          },{
            label:'港',
            value:'港'
          },{
            label:'澳',
            value:'澳'
          },{
            label:'渝',
            value:'渝'
          }
  ]
  return carNum;
}
